In [4]:
#1. Reading & displaying the data 
import pandas as pd
df = pd.read_csv('data.csv', delimiter = ',')
display(df)

,0,neuroticism_scores,extroversion_scores,openness_scores,agreeableness_scores,conscientiousness_scores
0,1,20.84,51.96,45.72,45.53,34.60
1,2,22.39,54.07,55.71,41.56,44.16
2,3,23.75,57.80,42.42,65.82,49.34
3,4,9.70,45.27,44.58,58.71,40.88
4,5,11.85,44.53,46.97,40.71,47.39
...,...,...,...,...,...,...
95,96,13.79,41.46,38.77,59.79,41.17
96,97,24.53,55.03,45.86,50.61,31.78
97,98,31.30,56.55,49.66,58.17,45.59
98,99,20.70,39.71,38.69,47.48,39.68
99,100,21.30,52.02,50.26,48.83,44.04

In [5]:
display(df.head(5))
display(df.info())

,0,neuroticism_scores,extroversion_scores,openness_scores,agreeableness_scores,conscientiousness_scores
0,1,20.84,51.96,45.72,45.53,34.60
1,2,22.39,54.07,55.71,41.56,44.16
2,3,23.75,57.80,42.42,65.82,49.34
3,4,9.70,45.27,44.58,58.71,40.88
4,5,11.85,44.53,46.97,40.71,47.39

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   0                         100 non-null    int64
 1   neuroticism_scores        100 non-null    float64
 2   extroversion_scores       100 non-null    float64
 3   openness_scores           100 non-null    float64
 4   agreeableness_scores      100 non-null    float64
 5   conscientiousness_scores  100 non-null    float64
dtypes: float64(5), int64(1)
memory usage: 4.8 KB

None

In [8]:
#     5.iii. Box-Plots for each numerical and categorical column (skip *subscribed* column), 
# and differentiate using *subscribed* column.
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure()

ValueError: Number of rows must be a positive integer, not 0